### ISSUE TITLE
Compound Protocol Local Deployment - ‘yarn run repl -s’: No such file or directory

### ISSUE THREAD

**Issue by chrishobcroft** [empowerthedao/compound-aragon-app#2]
Steps to recreate:

- Go to: https://github.com/empowerthedao/compound-aragon-app/tree/master/compound-protocol

- Run `npm install`

- Run `aragon devchain` in a separate terminal

- Run `rm networks/development*`

- See error as per https://github.com/empowerthedao/compound-aragon-app/issues/1

- Run `scenario/scen/deploy.scen -e dai_price=0.1,dai_cf=0.5,eth_cf=0.5`

- See error:

```
/usr/bin/env: ‘yarn run repl -s’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

Suggest having a section clearly listing the pre-requisites (including version numbers), and links to where they each can be installed.

**Comment by willjgriff** [comment]
See updated readme and try again.
