### ISSUE TITLE
Blank token page: Initialize with cETH for dao install

### ISSUE THREAD

**Issue by RuneOrion** [empowerthedao/compound-aragon-app#9]
When I run the following command to install the compound app with the cETH token, I get a blank token page:

`dao install <organisation_address> compound.open.aragonpm.eth --app-init-args <agent_proxy_address> ["'0xd6801a1dffcd0a410336ef88def4320d6df1883e'"] --environment aragon:rinkeby`

![Blank_Token_Compound](https://user-images.githubusercontent.com/3523880/65819374-4a192880-e24e-11e9-82c4-5bce2bf06028.png)

Any idea what is happening? If I run with cDAI token address, it works fine.

**Comment by chrishobcroft** [comment]
The scope for the first version of the app only includes DAI.

Here's the scope: https://github.com/empowerthedao/projects/blob/master/project1/Empower%20The%20DAO%20-%20Project%201%20-%20Scope.pdf

I believe that cTokens based on other ERC-20 tokens may also work.

I don't believe cTokens based on ETH are supported, @willjgriff can correct me if I'm wrong.

**Comment by chrishobcroft** [comment]
Closing
